# Site settings
baseurl = "https://backyarcornerrecords.com"
languageCode = "en-us"
title = "Backyard Corner Records"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
# googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Backyard Corner Records"
    subtitle = "Reggae/Dub label from south of France since 2018."
    author = "Lone Francis"
    description = "Backyard Corner Records is a label from Toulouse, France."
    keywords = "reggae, dub, label"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "More"

    # Footer text
    footertext = "[Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/) and [Hugo](http://gohugo.io)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']